  services:
    # 1. REDIS (Önbellekleme)
    redis:
      image: redis:latest
      container_name: taskreport_redis
      ports:
        - "6379:6379"
      restart: always

    # 2. RABBITMQ (Mesaj Kuyruğu & Yönetim Paneli)
    rabbitmq:
      image: rabbitmq:3-management
      container_name: taskreport_rabbitmq
      ports:
        - "5672:5672"   # C# API Bağlantı Portu
        - "15672:15672" # Web Yönetim Paneli
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      restart: always

    # 3. MINIO (Dosya & Resim Depolama)
    minio:
      image: minio/minio
      container_name: taskreport_minio
      ports:
        - "9000:9000" # API Portu
        - "9001:9001" # Web Yönetim Paneli
      environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
      command: server /data --console-address ":9001"
      restart: always